[config]
model = "gpt-4o-mini"
model_turbo = "gpt-4o-mini"
fallback_models = ["claude-3-5-sonnet-20241022"]
git_provider = "github"
publish_output = true
publish_output_progress = true
verbosity_level = 2
use_repo_settings_file = true
enable_help_text = true

[github]
# GitHub configuration for The Credit Pros
user_token = ""  # Set via environment variable GITHUB_TOKEN
deployment_type = "user"
ratelimit_retries = 5
base_url = "https://api.github.com"

[pr_reviewer]
# AI-powered code review with FCRA compliance focus
require_focused_review = true
require_score_review = false
require_tests_review = true
require_estimate_effort_to_review = true
require_security_review = true
enable_review_labels_effort = true
enable_review_labels_security = true
maximal_review_effort = 5
extra_instructions = """
CRITICAL: This is a credit repair application subject to FCRA regulations.

MANDATORY COMPLIANCE CHECKS:
1. FCRA Section 604 - Verify permissible purpose validation for all credit data access
2. PII Protection - Ensure all SSN, DOB, and financial data is encrypted/masked
3. Audit Trail - Validate comprehensive logging for all credit-related operations
4. Error Handling - Check for user-friendly error messages (no internal details)
5. Access Control - Verify role-based permissions for credit data access

CREDIT REPAIR DOMAIN VALIDATION:
- FICO score calculations must enforce 300-850 range
- Credit utilization calculations must handle edge cases
- Dispute workflows must track 30-day investigation timelines
- All credit bureau API calls must include retry logic and rate limiting

SECURITY REQUIREMENTS:
- No hardcoded credentials or API keys
- All database queries must use parameterized statements
- Input validation for all user-provided data
- Proper authentication and authorization checks

TESTING REQUIREMENTS:
- Minimum 80% test coverage for new code
- Include edge cases and error scenarios
- Mock external API calls (credit bureaus)
- Validate FCRA compliance in test scenarios
"""

[pr_reviewer.incremental]
enable_incremental_review = true
require_all_thresholds = false

[pr_code_suggestions]
enable_code_suggestions = true
commitable_code_suggestions = true
extra_instructions = """
Focus on:
1. FCRA compliance improvements
2. Credit calculation accuracy
3. PII data protection enhancements
4. Performance optimizations for credit workflows
5. Error handling improvements
6. Test coverage enhancements

Avoid suggesting:
- Changes that could impact FCRA compliance
- Modifications to audit trail logging
- Alterations to encryption/security measures
"""

[pr_description]
enable_pr_description = true
publish_description_as_comment = false
add_original_user_description = true
keep_original_user_title = true
extra_instructions = """
Include in PR description:
1. FCRA compliance impact assessment
2. Credit repair functionality changes
3. Security implications
4. Test coverage changes
5. Performance impact
6. Database migration requirements (if any)

STANDARDIZED FORMAT REQUIREMENTS:
- Use clear section headers with emojis
- Include impact assessment for each change type
- Document security considerations
- Specify testing requirements
- Note any breaking changes or migrations needed
- Link to related issues or documentation
"""

[pr_questions]
enable_pr_questions = true
extra_instructions = """
Ask questions about:
1. FCRA compliance validation approach
2. Credit calculation accuracy verification
3. PII data handling security measures
4. Test coverage for edge cases
5. Error handling for credit workflows
6. Performance impact on credit operations
"""

[pr_add_docs]
enable_pr_add_docs = true
docs_style = "google"
extra_instructions = """
Focus documentation on:
1. FCRA compliance requirements
2. Credit calculation methodologies
3. API usage patterns for credit data
4. Security considerations
5. Error handling approaches
6. Testing strategies
"""

[pr_update_changelog]
enable_pr_update_changelog = true
changelog_file = "CHANGELOG.md"
extra_instructions = """
Categorize changes as:
- FCRA Compliance
- Credit Calculations
- Security Enhancements
- Performance Improvements
- Bug Fixes
- Testing Improvements
"""

[pr_analyze]
enable_pr_analyze = true
extra_instructions = """
Analyze for:
1. FCRA compliance risks
2. Credit calculation accuracy
3. Security vulnerabilities
4. Performance bottlenecks
5. Test coverage gaps
6. Code maintainability
"""

[pr_similar_issue]
enable_pr_similar_issue = true

[pr_help]
enable_pr_help = true

[pr_config]
enable_pr_config = true

[local]
# Local development settings
description_path = ""
review_path = ""

[litellm]
# Cost optimization settings
drop_params = true
max_tokens = 4000
temperature = 0.1
