site_name: AI-SDLC Framework - Enhanced
site_description: AI-powered test generation and automated QA for Laravel + React + TypeScript projects
repo_url: https://github.com/nydamon/ai-sdlc-docs
site_author: Damon DeCrescenzo

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nydamon/ai-sdlc-docs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/thecreditpros
    - icon: fontawesome/solid/globe
      link: https://thecreditpros.com
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by creating an issue on GitHub.

copyright: |
  &copy; 2025 The Credit Pros. All rights reserved.<br>
  <strong>Enhanced AI-SDLC by Damon DeCrescenzo, CTO</strong><br>
  <em>AI test generation • Qase integration • Enterprise QA automation</em>

nav:
  - Home: README.md
  - Quick Start Guide: quick-start-simple.md
  - 📋 Manager Implementation Guide: implementation-guide-managers.md
  - 🧪 Testing & Validation: TESTING-README.md
  - Troubleshooting: troubleshooting-simple.md
  - Technical Guides:
      - Git Hooks Automation: git-hooks-automation.md
      - React Best Practices: react-best-practices-updated.md
      - Configuration Management: enhanced-config-management.md
      - Cursor IDE Guidelines: enhanced-cursor-guidelines.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
