site_name: AI-Powered SDLC
site_description: Central schematic, toolchain, and strategy for AI-augmented software development.
repo_url: https://github.com/nydamon/ai-sdlc-docs
theme:
  name: material
nav:
  - Home: README.md
  - AI Dev Stack Blueprint: ai_dev_stack_blueprint.md
  - AI First Playbook: ai-first-playbook.md
  - Governance & Safety: ai-governance-safety.md
  - Config Management: enhanced-config-management.md
  - Git Hooks Automation: git-hooks-automation.md
  - Monitoring & Observability: monitoring-observability.md
  - Project Specification: project_specification.md
  - React Best Practices: react-best-practices-updated.md
  - Rollout Gantt & Kanban: rollout_gantt_kanban.md
  - Readiness Checklist: rollout_readiness_checklist.md
  - Semantic Release Setup: semantic-release-setup.md
  - QA Strategy: testing-qa-strategy-revised.md
  - Architecture Diagram: sdlc_architecture_diagram.png
