site_name: AI-Powered SDLC
site_description: Unified architecture, toolchain, and strategic workflows for AI-augmented software development.
repo_url: https://github.com/nydamon/ai-sdlc-docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

nav:
  - Home: README.md
  - Getting Started:
      - Quick Start Guide: quick-start.md
      - Team Size Quick Starts: team-size-quickstarts.md
      - Implementation Roadmap: implementation-roadmap.md
      - Success Metrics: success-metrics.md
      - Migration Guide: migration-guide.md
      - Team Onboarding: team-onboarding-checklist.md
      - Cost Analysis: cost-analysis.md
  - Architecture:
      - AI-SDLC Architecture: sdlc-architecture-diagram.md
      - Tool Integration Matrix: tool-integration-matrix.md
      - AI Dev Stack Blueprint: ai_dev_stack_blueprint.md
      - Frontend Decision Tree: frontend-decision-tree.md
  - Strategy & Planning:
      - AI-First Playbook: ai-first-playbook.md
      - AI Integration Phases: ai-integration-phases.md
      - Governance & Safety: ai-governance-safety.md
      - Project Specification: project_specification.md
      - Readiness Checklist: rollout_readiness_checklist.md
      - Rollout Gantt & Kanban: rollout_gantt_kanban.md
  - Development Workflow:
      - Config Management: enhanced-config-management.md
      - Git Hooks Automation: git-hooks-automation.md
      - Semantic Release Setup: semantic-release-setup.md
      - React Best Practices: react-best-practices-updated.md
      - Enhanced Cursor Guidelines: enhanced-cursor-guidelines.md
  - QA & Monitoring:
      - Smart Testing Strategy: smart-testing.md
      - QA Strategy: testing-qa-strategy-revised.md
      - Monitoring & Observability: monitoring-observability.md
  - Support & Resources:
      - Troubleshooting Guide: troubleshooting-guide.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
