name: 🤖 AI Apply Safe Fixes

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: contains(github.event.pull_request.labels.*.name, 'apply-ai-fixes')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install deps
        run: npm ci --no-audit

      - name: Find latest healing learnings artifact
        id: find-artifact
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const artifacts = await github.paginate(github.rest.actions.listArtifactsForRepo, {
              owner,
              repo,
              per_page: 100,
            });
            const found = artifacts
              .filter(a => a.name === 'healing-learnings' && !a.expired)
              .sort((a,b) => new Date(b.created_at) - new Date(a.created_at))[0];
            core.setOutput('artifact_id', found ? String(found.id) : '');

      - name: Download healing learnings artifact
        if: steps.find-artifact.outputs.artifact_id != ''
        run: |
          echo "Downloading artifact ID: ${{ steps.find-artifact.outputs.artifact_id }}"
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.find-artifact.outputs.artifact_id }}/zip \
            -o healing-learnings.zip
          unzip -o healing-learnings.zip -d ./
          ls -la ./test-results || true

      - name: Check for existing learnings
        run: |
          if [ -d test-results ]; then
            echo "Existing learnings found, will apply them"
            ls -la test-results/ || true
          else
            echo "No existing learnings found, skipping E2E generation"
          fi

      - name: Apply safe fixes (lint/format)
        run: |
          npx eslint . --fix || true
          npx prettier --write "**/*.{js,jsx,ts,tsx,json,md,css,scss}" || true

      - name: Apply auto-heal learnings (if present)
        run: |
          if [ -d test-results ]; then
            npm run ai:apply-heal || true
          else
            echo "No test-results/ learnings to apply."
          fi

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(ai): apply safe auto-fixes"
          title: "chore(ai): apply safe auto-fixes"
          body: "Automated lint/format and optional selector healings."
          branch: ai/apply-safe-fixes-${{ github.run_id }}
          base: ${{ github.event.pull_request.head.ref }}
          labels: ai, automation
