name: 🧠 Generate AI Learnings

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to generate learnings for'
        required: true
        type: string
  issue_comment:
    types: [created]

jobs:
  generate-learnings:
    if: github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && contains(github.event.comment.body, '/generate-learnings'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install deps
        run: npm ci --no-audit

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E to generate learnings
        run: |
          npm run test:e2e || true
          npm run ai:auto-heal || true

      - name: Upload learnings
        uses: actions/upload-artifact@v4
        with:
          name: ai-learnings-${{ github.run_id }}
          path: test-results/
          retention-days: 7

      - name: Comment with learnings
        if: github.event.issue.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🧠 AI learnings generated! Use `/apply-fixes` to apply them.'
            })
