# SonarCloud Analysis - Main Branch Only
# Runs comprehensive code analysis on main branch without blocking development

name: 🔍 SonarCloud Analysis (Main Only)

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '20'

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  sonarcloud:
    name: 🔍 SonarCloud Analysis
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci --no-audit

      - name: 🧪 Run Tests with Coverage
        run: npm run test:coverage:sonar

      - name: 🔍 Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=TheCreditPros_dev_framework_demo
            -Dsonar.organization=thecreditpros
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300

      - name: 📊 Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-coverage
          path: coverage/
          retention-days: 7

      - name: 📝 Comment PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=TheCreditPros_dev_framework_demo
            -Dsonar.organization=thecreditpros
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
